services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      - network

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      - network
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9000"]
      interval: 5s
      timeout: 5s
      retries: 5

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - network

  sftp:
    build:
      context: ./requirements/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - wordpress_data:/home/ftpuser/upload
    networks:
      - network
    restart: unless-stopped


networks:
  network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind